baseURL: 'https://gabrioliv-garden.netlify.app'
languageCode: en-us
title: Garden
theme: PaperMod

buildDrafts: false
buildFuture: false
buildExpired: false

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: posts
      name: posts
      url: /posts/
      weight: 10

    - identifier: archive
      name: archive
      url: /archive/
      weight: 20

    - identifier: tags
      name: tags
      url: /tags/
      weight: 30

    - identifier: search
      name: search
      url: /search/
      weight: 40

params:
  env: production
  description: A Collection of Evolving Notes by GabriOliv
  author: gabrioliv

  keywords:
    - Digital Garden
    - Portfolio
    - Hugo

  images:
    - /images

  DateFormat: 02/01/2006
  defaultTheme: dark
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  disableShare: false
  disableHLJS: false # to disable highlightjs
  comments: false
  hidemeta: false
  searchHidden: false
  hideSummary: false
  showtoc: true
  tocopen: false

  editPost:
    URL: 'https://github.com/gabrioliv/garden/blob/master/content'
    Text: Suggest Changes
    appendFilePath: true

  profileMode:
    enabled: true
    title: Digital Garden
    subtitle: A Collection of Evolving Notes
    imageUrl: 'https://avatars.githubusercontent.com/u/43646296'
    imageTitle: Avatar
    imageWidth: 120
    imageHeight: 120

    buttons:
      - name: Posts
        url: /posts
      - name: Archive
        url: /archive
      - name: Tags
        url: /tags
      - name: Search
        url: /search

  socialIcons:
    - name: github
      url: 'https://github.com/gabrioliv/garden'
    - name: telegram
      url: 'https://t.me/Gab_Laureano'
    - name: linkedin
      url: 'https://linkedin.com/in/gabriel-o-77569a208/'

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

